Atomic writes
expo/json-file pull request #2
Opened 2017-07-07 21:05 UTC by wilzh40

Added a lockfile wrapper to each prototype function of `json-file` and made the writes atomic. 
Also added a couple of "integration" tests.
Right now there are still some race conditions if you have 2000 continuous updates to the same file.

2017-07-24 17:59 UTC, ide requested changes
thanks for writing the tests, that helps a lot

2017-07-24 17:59 UTC, ide commented on JsonFile.js
> +const wfap = (file, data) =>
name this `writeFileAtomicAsync`

2017-07-24 17:59 UTC, ide commented on JsonFile.js
> +      if (err) reject();
pass the error to `reject`, don't drop it on the floor

2017-07-24 17:59 UTC, ide commented on JsonFile.js
> +require('instapromise');
use https://github.com/ljharb/util.promisify instead

2017-07-24 17:59 UTC, ide commented on __tests__/JsonFile-test.js
> +const j = JSON.stringify;
looks unused, remove it (also just write this out instead of adding indirection)

2017-07-24 17:59 UTC, ide commented on JsonFile.js
> +    const promise = await fn(file, ...args);
this doesn't evaluate to a promise, it's the final result

2017-07-24 17:59 UTC, ide commented on JsonFile.js
> +const lockWrapper = fn => async (file, ...args) => {
instead of making this a function that returns a function, make this just invoke the passed-in function. this way there's less separation between the time `lockWrapper` is called and the actual locking+fn happen. something like

```js
callWithLock(() =>
  updateAsync(this.file, key, value, this._getOptions(options))
);
```

this also heads off the likelihood that someone calls two lock-wrapped functions that really should be inside of one critical section

2017-07-24 17:59 UTC, ide commented on JsonFile.js
> +    await lockFile.unlockSync(lockFileName);
this needs to happen in a `finally` clause in case this throws. we also don't want to catch errors, the caller wants to be able to handle them. the structure probably looks like:

```js
let result;
await lockAsync(...);

try {
  result = await fn(file, ...args);
} finally {
  lockfile.unlockSync(...); // no await since this is sync. also await in finally doesn't do what you expect 
}

return result
```

2017-07-24 17:59 UTC, ide commented on JsonFile.js
> +};
add newline

2017-07-24 17:59 UTC, ide commented on JsonFile.js
> +Object.assign(JsonFile, fns);
assign locking versions of the functions, these are part of the public interface

2017-07-24 18:53 UTC, wilzh40 commented on JsonFile.js
> +const lockWrapper = fn => async (file, ...args) => {
I have considered that but by creating a lockWrapper there is no way for me to extract the file name for the lock file. Perhaps something like
```
callWithLock(() =>
  updateAsync(this.file, key, value, this._getOptions(options)), 'fileName'
);
```

2017-07-24 19:21 UTC, wilzh40 commented on JsonFile.js
> +require('instapromise');
Why can't we use the built in util.promisify again?

2017-07-24 19:24 UTC, ide commented on JsonFile.js
> +require('instapromise');
It's enabled only on Node 8 but we generally support 6 and up (sometimes 7 and up)

2017-07-24 19:25 UTC, ide commented on JsonFile.js
> +const lockWrapper = fn => async (file, ...args) => {
sure, that's fine too. i'd recommend putting the callback as the last argument

2017-07-24 21:10 UTC, wilzh40 commented on JsonFile.js
> +Object.assign(JsonFile, fns);
Should both the class methods and the module methods use locking, or should there be an option to not do so?

2017-07-24 21:22 UTC, ide commented on JsonFile.js
> +Object.assign(JsonFile, fns);
Everything should use locking I think -- we're using file locks so that the locking applies across JsonFile instances and even processes, right?

2017-07-25 20:50 UTC, ide approved these changes

2017-07-25 21:11 UTC, merged

2017-07-25 21:12 UTC, wilzh40 commented
Right now just waiting on a version release.

2017-07-25 21:31 UTC, ide commented
Sure but can you fix the tests first? https://circleci.com/gh/expo/json-file/29

2017-07-25 22:33 UTC, wilzh40 commented
@ide Seemed like it was an eslint error, not a test error. Fixed and should be good to go.

2017-07-25 22:34 UTC, ide commented
Published to npm as v6.0.0 under the `next` dist-tag.